<section class="py-12 bg-gray-50">
    <div class="container mx-auto px-4">

        <!-- Filters -->
        <div class="flex flex-col md:flex-row justify-between items-center mb-8 gap-4">
            <div class="flex items-center space-x-2 px-4 py-1.5 bg-white rounded-full border border-gray-200 text-sm text-gray-600 w-full md:w-auto">
                <span class="whitespace-nowrap font-medium text-gray-900">Lọc theo:</span>
                <select class="border-none bg-transparent font-semibold text-gray-900 focus:ring-0 cursor-pointer outline-none">
                    <option>Địa điểm</option>
                    <option>Ngành nghề</option>
                    <option>Mức lương</option>
                </select>
            </div>

            <!-- Location Tabs -->
            <div class="flex items-center gap-2 overflow-x-auto w-full md:w-auto pb-2 md:pb-0 scrollbar-hide" id="location-tabs">
                <button class="p-2 border border-gray-200 rounded-full hover:bg-gray-100 text-gray-500">
                    <i class="bi bi-chevron-left"></i>
                </button>

                <!-- Buttons generated by JS or hardcoded below. Hardcoding for clarity -->
                <button class="filter-btn px-4 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors border bg-[var(--accent-color)] text-white border-[var(--accent-color)] shadow-md" data-loc="Tất cả">Tất cả</button>
                <button class="filter-btn px-4 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors border bg-white text-gray-600 border-gray-200 hover:border-gray-300 hover:bg-gray-50" data-loc="Hà Nội">Hà Nội</button>
                <button class="filter-btn px-4 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors border bg-white text-gray-600 border-gray-200 hover:border-gray-300 hover:bg-gray-50" data-loc="Đà Nẵng">Đà Nẵng</button>
                <button class="filter-btn px-4 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors border bg-white text-gray-600 border-gray-200 hover:border-gray-300 hover:bg-gray-50" data-loc="TP. Hồ Chí Minh">TP. Hồ Chí Minh</button>
                <button class="filter-btn px-4 py-1.5 rounded-full text-sm whitespace-nowrap transition-colors border bg-white text-gray-600 border-gray-200 hover:border-gray-300 hover:bg-gray-50" data-loc="Cần Thơ">Cần Thơ</button>

                <button class="p-2 border border-gray-200 rounded-full hover:bg-gray-100 text-gray-500">
                    <i class="bi bi-chevron-right"></i>
                </button>
            </div>
        </div>

        <!-- Job Grid -->
        <div id="job-grid" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">

            @foreach(range(1,9) as $number)
            <!-- Job 1 -->
            <div class="job-card bg-white rounded-xl shadow-sm border border-gray-100 p-3 hover:shadow-lg transition-shadow duration-300 group cursor-pointer" data-location="TP. Hồ Chí Minh">
                <div class="flex items-start gap-4">
                    <div class="w-16 h-16 rounded-lg bg-white border border-gray-100 flex-shrink-0 overflow-hidden p-1 shadow-sm">
                        <img src="https://picsum.photos/id/101/64/64" alt="Company Logo" class="w-full h-full object-contain" />
                    </div>
                    <div class="flex-1 min-w-0">
                        <h3 class="text-base font-bold text-gray-900 leading-snug mb-1 group-hover:text-primary transition-colors line-clamp-2">Nhân viên chăm sóc khách hàng</h3>
                        <p class="text-xs text-black uppercase tracking-wide font-medium mb-1">Mebipha</p>

                         <div class="space-y-2">
                            <div class="flex items-center text-sm text-gray-600">
                                <i class="bi bi-geo w-4 h-4 mr-2 text-gray-400"></i>
                                <span class="truncate">TP. Hồ Chí Minh</span>
                            </div>
                            <div class="flex items-center justify-between text-sm text-green-600 font-medium">
                                <div class="">
                                    <i class="bi bi-coin w-4 h-4 mr-2"></i>
                                    <span>7 - 10 triệu</span>
                                </div>
                                <div class="text-gray-500">2 ngày trước</div>
                            </div>
                        </div>
                        <div class="border-t border-gray-50 flex items-center justify-between text-xs text-gray-400">
                            <div class="flex items-center">
                                
                            </div>
                        </div>
                    </div>
                </div>
               
            </div>
            @endforeach
        </div>

        <!-- Pagination -->
        <div class="flex justify-center mt-12">
            <div class="flex items-center space-x-2">
                <button class="w-8 h-8 flex items-center justify-center rounded-md border border-gray-200 text-gray-500 hover:bg-gray-50 text-sm">
                    <i data-lucide="chevron-left" class="w-4 h-4"></i>
                </button>
                <button class="w-8 h-8 flex items-center justify-center rounded-md bg-primary text-white text-sm font-bold shadow-md">1</button>
                <button class="w-8 h-8 flex items-center justify-center rounded-md border border-gray-200 text-gray-600 hover:bg-gray-50 text-sm">2</button>
                <button class="w-8 h-8 flex items-center justify-center rounded-md border border-gray-200 text-gray-600 hover:bg-gray-50 text-sm">3</button>
                <span class="text-gray-400">...</span>
                <button class="w-8 h-8 flex items-center justify-center rounded-md border border-gray-200 text-gray-600 hover:bg-gray-50 text-sm">7</button>
                <button class="w-8 h-8 flex items-center justify-center rounded-md border border-gray-200 text-gray-500 hover:bg-gray-50 text-sm">
                    <i data-lucide="chevron-right" class="w-4 h-4"></i>
                </button>
            </div>
        </div>
    </div>
</section>